Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('users/', include('users.urls'))
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.index, name='index'),
    path('new_post', views.new_post, name='new_post'),
     path('edit/<int:post_id>/', views.edit_post, name='edit_post'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

blogs/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User

# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField(max_length=10000)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost

class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Add title'}),
            'text': forms.Textarea(attrs={'placeholder': 'Add text'}),
        }

blogs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import BlogPost
from .forms import PostForm
from django.contrib.auth.decorators import login_required
from django.http import Http404
# Create your views here.

@login_required
def index(request):
    posts = BlogPost.objects.order_by('date_added') 
    context = {'posts' : posts}
    if request.method == 'POST':
        return redirect('blogs:new_post')
    return render(request, 'blogs/index.html', context)

@login_required
def new_post(request):
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(data=request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.owner = request.user
            new_post.save()
            return redirect('blogs:index')
    context = {'form': form}
    return render(request, 'blogs/new_post.html', context)   

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(BlogPost, id=post_id)
    if request.method != 'POST':
        form = PostForm(instance=post)
    else:
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('blogs:index')
    context = {'form': form, 'post': post}
    return render(request, 'blogs/edit_post.html', context)

def check_topic_owner(owner, user):
    if owner != user:
        raise Http404

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blogs:index')
    context = {'form' : form}
    return render(request, 'registration/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">Posts</a>
        <a class="navbar-brand" href="{% url 'blogs:new_post' %}">Add a new post</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span></button>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <span class="navbar-text m-3" >Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <form class="d-flex" method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-success m-3" type="submit">logout</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <form class="d-flex" method="post" action="{% url 'users:login' %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-success m-3" type="submit">login</button>
                    </form>
                </li>
                <li class="nav-item">
                    <form class="d-flex" method="post" action="{% url 'users:register' %}">
                        {% csrf_token %}
                        <button class="btn btn-outline-success m-3" type="submit">register</button>
                    </form>
                </li>
            {% endif %}
        </ul>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div class="container mt-4">
            <div class="card">
                <div class="card-body">
                    {% block content %}{% endblock content %}
                </div>
            </div>
        </div>
    </main>
</body>
</html>

blogs/templates/blogs/edit_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Edit post:</h1>
{% endblock page_header %}

{% block content %}
    
    <form action="{% url 'blogs:edit_post' post.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}     
        
    </form>
{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block page_header %}
    <h1>Posts</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for post in posts %}
            <li>
                <h2>{{post.title}}</h2>
                <div>{{post.text}}</div>
                <div><p class="font-weight-light">{{post.date_added}}</p></div>
                <div><p class="font-italic">By {{post.owner}}</p></div>
                <a href="{% url 'blogs:edit_post' post.id %}">Edit</a>
            </li>
        {% empty %}
            <li>
                No posts have been added
            </li>
        {% endfor %}
    </ul>
{% endblock content %}

blogs/templates/blogs/new_post.html
{% extends "blogs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h1>Add a new post:</h1>
{% endblock page_header %}

{% block content %}  
    <form action="{% url 'blogs:new_post' %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}     
    </form>
    
{% endblock content %}